# Generated by Django 4.1.2 on 2023-01-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_datapelanggan_datapenjualan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datapelanggan',
            new_name='Datapeminjaman',
        ),
        migrations.RenameField(
            model_name='datapeminjaman',
            old_name='jenispembelian',
            new_name='jenisbuku',
        ),
        migrations.RenameField(
            model_name='datapeminjaman',
            old_name='tglbeli',
            new_name='tglpinjam',
        ),
    ]
