# Generated by Django 4.1.2 on 2023-01-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_datapelanggan_datapeminjaman_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Databuku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('judul', models.CharField(max_length=20)),
                ('penulis', models.CharField(max_length=15)),
                ('penerbit', models.CharField(max_length=20)),
                ('tahunterbit', models.IntegerField()),
                ('tebal', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Datapenjualan',
        ),
    ]
